# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bc97bcadc309956998f72f4a4d310fdb"
name = "checkout-test"
handle = "checkout-test-183"
application_url = "https://base-wit-nh-imports.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "alo-test-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://base-wit-nh-imports.trycloudflare.com/auth/callback",
  "https://base-wit-nh-imports.trycloudflare.com/auth/shopify/callback",
  "https://base-wit-nh-imports.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
